server:
  port: 8070

spring:
  application:
    name: frequency-risk-indicator-service
  datasource:
    url: jdbc:h2:mem:proton6
    username: mayank
    password: mayank
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console

weather:
  url: https://api.weatherapi.com/v1