server:
  port: 8070

spring:
  application:
    name: pam-asset-transparency
  datasource:
    url: jdbc:postgresql://localhost:5432/proton6
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

weather:
  url: https://api.weatherapi.com/v1