services:
  - type: web
    name: spring-boot-app
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/frequency-risk-detection-inertia-control-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: jdbc:h2:mem:proton6
